=== OscarLlaPar/2021_LMSGI_OLP/EX02_20210309_OSCARLLAMASPARRA/mapaestelar.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/mapaestelar.dtd

-->


<!ELEMENT mapa (constelacion+,estrella+)>
<!ATTLIST mapa
    xmlns:xsi CDATA #IMPLIED
    xsi:noNamespaceSchemaLocation CDATA #IMPLIED>
<!ELEMENT constelacion (nombre,superficie,estrellas,objetos,colindantes,observacion)>
<!ATTLIST constelacion
    nombreLatin ID #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT superficie (#PCDATA)>
<!ELEMENT estrellas (asterismo,masBrillante)>
<!ATTLIST estrellas
    nestrellas CDATA #REQUIRED>
<!ELEMENT asterismo (#PCDATA)>
<!ELEMENT masBrillante (#PCDATA)>
<!ATTLIST masBrillante
    luminosidad CDATA #REQUIRED>
<!ELEMENT objetos (cumulo,nebulosa,galaxia,cuasar,lluviameteo*)>
<!ELEMENT cumulo (#PCDATA)>
<!ELEMENT nebulosa (#PCDATA)>
<!ELEMENT galaxia (#PCDATA)>
<!ELEMENT cuasar (#PCDATA)>
<!ELEMENT lluviameteo (#PCDATA)>
<!ELEMENT colindantes (nombre)*>
<!ELEMENT observacion (hemisferio,mes,hora)>
<!ELEMENT hemisferio (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT hora (#PCDATA)>
<!ELEMENT estrella (nombre,const,distancia,luminosidad,temperatura,masa)>
<!ELEMENT const (#PCDATA)>
<!ELEMENT distancia (#PCDATA)>
<!ATTLIST distancia
    medida CDATA "aÃ±os luz">
<!ELEMENT luminosidad (#PCDATA)>
<!ATTLIST luminosidad
    medida CDATA #FIXED "soles">
<!ELEMENT temperatura (#PCDATA)>
<!ATTLIST temperatura
    medida  CDATA "K">
<!ELEMENT masa (#PCDATA)>
<!ATTLIST masa
    medida CDATA "soles">

=== OscarLlaPar/2021_LMSGI_OLP/EX02_20210309_OSCARLLAMASPARRA/mapaestelar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapa SYSTEM "mapaestelar.dtd">
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<mapa
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='mapaestelar.xsd'>
    <constelacion nombreLatin="UrsaMaior">
        <nombre>Osa Mayor</nombre>
        <superficie>1279.7</superficie>
        <estrellas nestrellas="209">
            <asterismo>7</asterismo>
            <masBrillante luminosidad="1.77">Alioth</masBrillante>
        </estrellas>
        <objetos>
            <cumulo>false</cumulo>
            <nebulosa>true</nebulosa>
            <galaxia>true</galaxia>
            <cuasar>false</cuasar>
            <lluviameteo>Kappa Ursa Mayóridas</lluviameteo>
            <lluviameteo>Lambda Ursa Mayóridas</lluviameteo>
            <lluviameteo>Psi Ursa Mayóridas</lluviameteo>
            <lluviameteo>Ursa Mayóridas de octubre</lluviameteo>
        </objetos>
        <colindantes>
            <nombre>Bootes</nombre>
            <nombre>Camelopardalis</nombre>
            <nombre>Canes Venatici</nombre>
            <nombre>Draco</nombre>
            <nombre>Leo</nombre>
            <nombre>Leo Minor</nombre>
            <nombre>Lynx</nombre>
        </colindantes>
        <observacion>
            <hemisferio>Norte</hemisferio>
            <mes>04</mes>
            <hora>21:00:00</hora>
        </observacion>
    </constelacion>
    <estrella>
        <nombre>Alioth</nombre>
        <const>Osa Mayor</const>
        <distancia medida="años luz">81</distancia>
        <luminosidad medida="soles">108</luminosidad>
        <temperatura medida="K">9400</temperatura>
        <masa medida="soles">3</masa>
    </estrella>
</mapa>
