=== OscarLlaPar/2021_LMSGI_OLP/ud04/04.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/04.dtd

-->


<!ELEMENT horario (hora)+>
<!ATTLIST horario
    xmlns:xsi CDATA #IMPLIED
    xsi:noNamespaceSchemaLocation CDATA #IMPLIED>
<!ELEMENT hora (dia_sem)+>
<!ATTLIST hora
    entrada CDATA #IMPLIED
    salida CDATA #IMPLIED>
<!ELEMENT dia_sem (modulo,profesor+)>
<!ATTLIST dia_sem
    dia CDATA #IMPLIED
    hora CDATA #IMPLIED>
<!ELEMENT modulo (#PCDATA)>
<!ELEMENT profesor (#PCDATA)>

=== OscarLlaPar/2021_LMSGI_OLP/ud04/04.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE horario SYSTEM "04.dtd">
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<horario
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='Schema04.xsd'>
    <hora entrada="08:30" salida="09:20">
            <dia_sem dia="lunes" hora="1">
                <modulo>Entornos de Desarrollo</modulo>
                <profesor>MUP</profesor>
            </dia_sem>
            <dia_sem dia="martes" hora="2">
                <modulo>Bases de Datos</modulo>
                <profesor>HRO</profesor>
            </dia_sem>
            <dia_sem dia="miercoles" hora="2">
                <modulo>Programación</modulo>
                <profesor>ACF</profesor>
            </dia_sem>
            <dia_sem dia="jueves" hora="2">
                <modulo>Lenguaje de Marcas y Sistemas de Gestion Informática</modulo>
                <profesor>ARN</profesor>
                <profesor>HRO</profesor>
            </dia_sem>
            <dia_sem dia="viernes" hora="1">
                <modulo>Entornos de Desarrollo</modulo>
                <profesor>MUP</profesor>
            </dia_sem>
        </hora>
        <hora entrada="09:20" salida="10:10">
            <dia_sem dia="lunes" hora="2">
                <modulo>Sistemas Informáticos</modulo>
                <profesor>NCB</profesor>
            </dia_sem>
            <dia_sem dia="viernes" hora="2">
                <modulo>Sistemas Informáticos</modulo>
                <profesor>NCB</profesor>
            </dia_sem>
        </hora>
        <hora entrada="10:10" salida="11:00">
            <dia_sem dia="martes" hora="2">
                <modulo>Programación</modulo>
                <profesor>ACF</profesor>
            </dia_sem>
            <dia_sem dia="miercoles" hora="1">
                <modulo>Formación y Orientación Laboral</modulo>
                <profesor>MAM</profesor>
            </dia_sem>
            <dia_sem dia="jueves" hora="2">
                <modulo>Programación</modulo>
                <profesor>ACF</profesor>
            </dia_sem>
        </hora>
        <hora entrada="11:00" salida="11:50">
            <dia_sem dia="lunes" hora="2">
                <modulo>Programación</modulo>
                <profesor>ACF</profesor>
            </dia_sem>
            <dia_sem dia="miercoles" hora="2">
                <modulo>Bases de Datos</modulo>
                <profesor>HRO</profesor>
            </dia_sem>
            <dia_sem dia="viernes" hora="1">
                <modulo>Formación y Orientación Laboral</modulo>
                <profesor>MAM</profesor>
            </dia_sem>
        </hora>
        <hora entrada="12:15" salida="13:05">
            <dia_sem dia="martes" hora="2">
                <modulo>Lenguaje de Marcas y Sistemas de Gestion Informática</modulo>
                <profesor>ARN</profesor>
                <profesor>HRO</profesor>
            </dia_sem>
            <dia_sem dia="jueves" hora="2">
                <modulo>Sistemas Informáticos</modulo>
                <profesor>NCB</profesor>
            </dia_sem>
            <dia_sem dia="viernes" hora="2">
                <modulo>Bases de Datos</modulo>
                <profesor>HRO</profesor>
            </dia_sem>
        </hora>
        <hora entrada="13:05" salida="13:55">
            <dia_sem dia="lunes" hora="1">
                <modulo>Formación y Orientación Laboral</modulo>
                <profesor>MAM</profesor>
            </dia_sem>
            <dia_sem dia="miercoles" hora="1">
                <modulo>Entornos de Desarrollo</modulo>
                <profesor>MUP</profesor>
            </dia_sem>
        </hora>
</horario>
