=== OscarLlaPar/2021_LMSGI_OLP/ud04/11.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!--
    TODO define vocabulary identification data
    PUBLIC ID  : -//vendor//vocabulary//EN
    SYSTEM ID  : http://server/path/__NAME__
-->

<!-- TODO define your own vocabulary/syntax. Example follows:  -->
<!ELEMENT catalogo (portatil)*>
<!ATTLIST catalogo
    xmlns:xsi CDATA #IMPLIED
    xsi:noNamespaceSchemaLocation CDATA #IMPLIED>
<!ELEMENT portatil (referencia, nombre, fabricante, procesador, ram, disco, pantalla, grafica)>
<!ELEMENT referencia (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT fabricante EMPTY>
<!ATTLIST fabricante
    nombre (LENOVO|HP|MSI|APPLE|ASUS|DELL|DESCONOCIDO) #REQUIRED>
<!ELEMENT procesador (nombre+, cache, nprocesadores, velocidad)>
<!ELEMENT cache (#PCDATA)>
<!ATTLIST cache 
    tamanyo (MB|GB|TB) "GB">
<!ELEMENT nprocesadores (#PCDATA)>
<!ELEMENT velocidad (#PCDATA)>
<!ATTLIST velocidad
    medida CDATA #FIXED "GHz">
<!ELEMENT ram (memoria, tipo)>
<!ELEMENT memoria (#PCDATA)>
<!ATTLIST memoria 
    medida (MB|GB|TB) "GB">
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT disco (tipo, capacidad)>
<!ELEMENT capacidad (#PCDATA)>
<!ATTLIST capacidad
    medida (MB|GB|TB) "GB">
<!ELEMENT pantalla (dimension, resolucion, rmaxima?)>
<!ELEMENT dimension (#PCDATA)>
<!ELEMENT resolucion (#PCDATA)>
<!ELEMENT rmaxima (#PCDATA)>
<!ELEMENT grafica (#PCDATA)>
<!ATTLIST __ROOT__ version CDATA #REQUIRED>

=== OscarLlaPar/2021_LMSGI_OLP/ud04/11.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalogo SYSTEM "11.dtd">
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<catalogo 
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='Schema10.xsd'>
    <portatil>
        <referencia>HP12345</referencia>
        <nombre>HP 15-DA0204NS</nombre>
        <fabricante nombre="HP"/>
        <procesador>
            <nombre>Intel Core i3-7020U</nombre>
            <cache tamanyo="MB">500</cache>
            <nprocesadores>2</nprocesadores>
            <velocidad medida="GHz">2,3</velocidad>
        </procesador>
        <ram>
            <memoria medida="GB">8</memoria>
            <tipo>DDR4</tipo>
        </ram>
        <disco>
            <tipo>SSD</tipo>
            <capacidad medida="GB">500</capacidad>
        </disco>
        <pantalla>
            <dimension>27 pulgadas</dimension>
            <resolucion>1266x768</resolucion>
            <rmaxima>1366x768</rmaxima>
        </pantalla>
        <grafica>Nvidia GTX 720</grafica>
    </portatil>
    <portatil>
        <referencia>LE12345</referencia>
        <nombre>LENOVO IDEAPAD S145</nombre>
        <fabricante nombre="LENOVO"/>
        <procesador>
            <nombre>Intel Core i3-8145U</nombre>
            <cache tamanyo="MB">500</cache>
            <nprocesadores>1</nprocesadores>
            <velocidad medida="GHz">2,1</velocidad>
        </procesador>
        <ram>
            <memoria medida="GB">8</memoria>
            <tipo>DDR4</tipo>
        </ram>
        <disco>
            <tipo>HDD</tipo>
            <capacidad medida="TB">1</capacidad>
        </disco>
        <pantalla>
            <dimension>23 pulgadas</dimension>
             <resolucion>1266x768</resolucion>
        </pantalla>
        <grafica>Intel UHD Graphics 620</grafica>
    </portatil>
</catalogo>
