=== OscarLlaPar/2021_LMSGI_OLP/ud04/13.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/13.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE usoredes SYSTEM "13.dtd">

    <usoredes>
    ...
    </usoredes>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT usoredes (formulario)*>
<!ATTLIST usoredes
    xmlns:xsi CDATA #IMPLIED
    xsi:noNamespaceSchemaLocation CDATA #IMPLIED>
<!ELEMENT formulario (datos,uso,opinion)>
<!ELEMENT datos (nombre,apellidos,localidad,sexo?,telefono)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT localidad (#PCDATA)>
<!ATTLIST localidad
    provincia CDATA #IMPLIED>
<!ELEMENT sexo (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT uso (redes,dispositivo)>
<!ELEMENT redes (red)+>
<!ELEMENT red (#PCDATA)>
<!ELEMENT dispositivo (#PCDATA)>
<!ELEMENT opinion (color,adiccion,sugerencia)>
<!ELEMENT color (#PCDATA)>
<!ELEMENT adiccion EMPTY>
<!ATTLIST adiccion
    value CDATA #IMPLIED>
<!ELEMENT sugerencia (#PCDATA)>

=== OscarLlaPar/2021_LMSGI_OLP/ud04/13.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE usoredes SYSTEM "13.dtd">
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<usoredes
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='Schema13.xsd'>
    <formulario>
        <datos>
            <nombre>Ã“scar</nombre>
            <apellidos>Llamas Parra</apellidos>
            <localidad provincia="Zamora">Benavente</localidad>
            <sexo>Hombre</sexo>
            <telefono>123456789</telefono>
        </datos>
        <uso>
            <redes>
                <red>Instagram</red>
                <red>Twitter</red>
                <red>Facebook</red>
            </redes>
            <masusada>
                <instagram horasdia="5"/>
            </masusada>
            <dispositivo>Ordenador</dispositivo>
        </uso>
        <opinion>
            <color>#000000</color>
            <adiccion value="10"/>
            <sugerencia>Escribir sugerencia</sugerencia>
        </opinion>
    </formulario>
</usoredes>
