=== OscarLlaPar/2021_LMSGI_OLP/ud04/Schema10.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="horario">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="modulos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="modulo" type="xs:string" maxOccurs="unbounded"/>   
                        </xs:sequence>
                        <xs:attribute name="codM" type="xs:ID" use="required"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="profesores">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="profesor" type="xs:string" maxOccurs="unbounded"/>   
                        </xs:sequence>
                        <xs:attribute name="codP" type="xs:ID" use="required"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="imparte">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="asignatura" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="codM" type="xs:IDREFS" use="required"/>
                                    <xs:attribute name="codProfesor" type="xs:IDREFS" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="codM" type="xs:IDREFS" use="required"/>
                        <xs:attribute name="codProfesor" type="xs:IDREFS" use="required"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="grupo">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="hora">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="dia_sem">
                                            <xs:complexType>
                                                <xs:attribute name="dia" type="xs:string"/>
                                                <xs:attribute name="num" type="xs:integer"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="entrada" type="xs:string"/>
                                    <xs:attribute name="salida" type="xs:string"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="idgrupo" type="xs:ID"/>
                        <xs:attribute name="codT" type="xs:IDREFS"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== OscarLlaPar/2021_LMSGI_OLP/ud04/10.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE horario SYSTEM "10.dtd">
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<horario curso="2020-21" 
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='Schema10.xsd'>
    <modulos>
        <modulo codM="EDD">Entornos de Desarrollo</modulo>
        <modulo codM="LMSGI">Lenguaje de Marcas y Sistemas de Gestion Informática</modulo>
        <modulo codM="PROG">Programación</modulo>
        <modulo codM="BBDD">Bases de Datos</modulo>
        <modulo codM="FOL">Formación y Orientación Laboral</modulo>
        <modulo codM="SINF">Sistemas Informáticos</modulo>
    </modulos>
    <profesores>
        <profesor codP="MUP">Marcos Unzueta Puente</profesor>
        <profesor codP="ARN">Amor Rodriguez Navarro</profesor>
        <profesor codP="ACF">Ambrosio Casado Fernandez</profesor>
        <profesor codP="HRO">Hermelinda Ramos Osorio</profesor>
        <profesor codP="MAM">María del Cielo Alejo Mulas</profesor>
        <profesor codP="NCB">Natividad Crespo Belver</profesor>
    </profesores>
    <imparte>
        <asignatura codM="EDD" codProfesor="MUP"/>
        <asignatura codM="LMSGI" codProfesor="ARN"/>
        <asignatura codM="PROG" codProfesor="ACF"/>
        <asignatura codM="BBDD" codProfesor="HRO"/>
        <asignatura codM="FOL" codProfesor="MAM"/>
        <asignatura codM="SINF" codProfesor="NCB"/>
    </imparte>
    <grupo idgrupo="DAW1" codT="MUP">
        <hora entrada="08:30" salida="09:20">
            <dia_sem dia="lunes" num="1">Entornos de Desarrollo</dia_sem>
            <dia_sem dia="martes" num="2">Bases de Datos</dia_sem>
            <dia_sem dia="miercoles" num="2">Programación</dia_sem>
            <dia_sem dia="jueves" num="2">Lenguaje de Marcas y Sistemas de Gestion Informática</dia_sem>
            <dia_sem dia="viernes" num="1">Entornos de Desarrollo</dia_sem>
        </hora>
        <hora entrada="09:20" salida="10:10">
            <dia_sem dia="lunes" num="2">Sistemas Informáticos</dia_sem>
            <dia_sem dia="viernes" num="2">Sistemas Informáticos</dia_sem>
        </hora>
        <hora entrada="10:10" salida="11:00">
            <dia_sem dia="martes" num="2">Programación</dia_sem>
            <dia_sem dia="miercoles" num="1">Formación y Orientación Laboral</dia_sem>
            <dia_sem dia="jueves" num="2">Programación</dia_sem>
        </hora>
        <hora entrada="11:00" salida="11:50">
            <dia_sem dia="lunes" num="2">Programación</dia_sem>
            <dia_sem dia="miercoles" num="2">Bases de Datos</dia_sem>
            <dia_sem dia="viernes" num="1">Formación y Orientación Laboral</dia_sem>
        </hora>
        <hora entrada="12:15" salida="13:05">
            <dia_sem dia="martes" num="2">Lenguaje de Marcas y Sistemas de Gestion Informática</dia_sem>
            <dia_sem dia="jueves" num="2">Sistemas Informáticos</dia_sem>
            <dia_sem dia="viernes" num="2">Bases de Datos</dia_sem>
        </hora>
        <hora entrada="13:05" salida="13:55">
            <dia_sem dia="lunes" num="1">Formación y Orientación Laboral</dia_sem>
            <dia_sem dia="miercoles" num="1">Entornos de Desarrollo</dia_sem>
        </hora>
    </grupo>
</horario>
