=== OscarLlaPar/2021_LMSGI_OLP/ud04/Schema3.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="tabla">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="row" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="descripcion" type="xs:string"/>
                            <xs:element name="fecha">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="dia" type="xs:byte"/>
                                        <xs:element name="mes" type="xs:byte"/>
                                        <xs:element name="anyo" type="xs:integer"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== OscarLlaPar/2021_LMSGI_OLP/ud04/03.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!DOCTYPE tabla[
    <!ELEMENT descripcion (#PCDATA)>
    <!ELEMENT dia (#PCDATA)>
    <!ELEMENT mes (#PCDATA)>
    <!ELEMENT anyo (#PCDATA)>
    <!ELEMENT fecha (dia, mes, anyo)>
    <!ELEMENT row (descripcion, fecha)>
    <!ELEMENT tabla (row+)>
    <!ATTLIST tabla
        xmlns:xsi CDATA #IMPLIED
        xsi:noNamespaceSchemaLocation CDATA #IMPLIED>
]>

<tabla xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='Schema3.xsd'>
    <row>
        <descripcion>Se funda YouTube</descripcion>
        <fecha>
             <dia>15</dia>
            <mes>2</mes>
            <anyo>2005</anyo>
        </fecha>
    </row>
    <row>
        <descripcion>Se funda Google</descripcion>
        <fecha>    
            <dia>4</dia>
            <mes>9</mes>
            <anyo>1998</anyo>
        </fecha>
    </row>
    <row>
        <descripcion>Se funda Facebook</descripcion>
        <fecha>
            <dia>4</dia>
            <mes>2</mes>
            <anyo>2004</anyo>
        </fecha>
    </row>
</tabla>
